name: 'X Post Action'
description: 'Post a message to X'
author: 'captradeoff'
branding:
  icon: message-circle
  color: black
inputs:
  appKey:
    description: 'The app key'
    required: true
  appSecret:
    description: 'The app secret'
    required: true
  accessToken:
    description: 'The access token'
    required: true
  accessSecret:
    description: 'The access secret'
    required: true
  message:
    description: 'The message to post'
    required: true
    default: 'Hello, world!'
  community-id:
    description: 'The ID of the community to post to'
    required: false
    default: null
outputs:
  post-id:
    description: 'The ID of the post'
runs:
  using: 'node20'
  main: 'dist/index.js'